server:
  port: 80
spring:
  mvc:
    view:
      prefix: classpath:/templates
      suffix: .html
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true
mybatis:
  mapper-locations:classpath:mapper/*.xml;